using System.ComponentModel.DataAnnotations;

namespace Distributor.Api.Contracts;

public sealed record LoginRequest([param: Required, StringLength(80)] string Username, [param: Required] string Password);
public sealed record UpdateAdminCredentialsRequest([param: Required, RegularExpression(@"^[a-zA-Z0-9_.-]{3,80}$")] string Username, [param: Required] string CurrentPassword, string? NewPassword);
public sealed record CreateUserRequest(Guid? CompanyId, [param: Required, StringLength(160)] string Name, [param: Required, RegularExpression(@"^[a-zA-Z0-9_.-]{3,80}$")] string Username, [param: Required] string Password, [param: Required] string Role, [param: StringLength(120)] string? Territory = null, bool Active = true, [param: StringLength(500)] string Address = "", [param: RegularExpression(@"^(?:[0-9]{9}[vVxX]|[0-9]{12})$", ErrorMessage = "Enter a valid Sri Lankan NIC.")] string Nic = "", [param: PhoneNumber] string Phone = "", [param: OptionalEmail, StringLength(254)] string Email = "", [param: Range(typeof(decimal), "0", "999999999999.99")] decimal? MonthlyTarget = null);
public sealed record UpdateUserRequest(Guid? CompanyId, [param: Required, StringLength(160)] string Name, [param: Required] string Role, bool Active, [param: StringLength(120)] string? Territory = null, [param: StringLength(500)] string Address = "", [param: RegularExpression(@"^(?:[0-9]{9}[vVxX]|[0-9]{12})$", ErrorMessage = "Enter a valid Sri Lankan NIC.")] string Nic = "", [param: PhoneNumber] string Phone = "", [param: OptionalEmail, StringLength(254)] string Email = "", [param: Range(typeof(decimal), "0", "999999999999.99")] decimal? MonthlyTarget = null);
public sealed record ChangePasswordRequest([param: Required] string CurrentPassword, [param: Required] string NewPassword);
public sealed record AdminResetPasswordRequest([param: Required] string NewPassword);
public sealed record BrandingSettingsRequest([param: Required, StringLength(120)] string Name, string LogoDataUrl = "");
public sealed record CompanyRequest([param: Required, StringLength(80)] string Code, [param: Required, StringLength(160)] string Name, [param: StringLength(160)] string ContactName, [param: PhoneNumber] string Phone, [param: StringLength(500)] string Address, bool Active = true);
public sealed record ShopRequest([param: NotEmptyGuid] Guid CompanyId, [param: Required, StringLength(80)] string Code, [param: Required, StringLength(160)] string Name, [param: StringLength(160)] string ContactName, [param: PhoneNumber] string Phone, [param: StringLength(500)] string Address, [param: StringLength(120)] string City, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal CreditLimit, bool Active = true);
public sealed record ProductRequest([param: NotEmptyGuid] Guid CompanyId, [param: Required, StringLength(100)] string Sku, [param: Required, StringLength(100)] string Barcode, [param: Required, StringLength(200)] string Name, [param: StringLength(120)] string Category, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal SellingPrice, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal CostPrice, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal ReorderLevel, [param: BusinessDate] DateOnly? ExpiryDate, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal OpeningStock = 0, bool Active = true, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal? Mrp = null);
public sealed record StockAdjustmentRequest([param: Range(typeof(decimal), "0.000001", "999999999999.99")] decimal Quantity, [param: Required, RegularExpression("(?i)^(IN|OUT)$")] string Direction, [param: StringLength(500)] string Notes, [param: StringLength(80)] string? Reason = null);
public sealed record StockInLineRequest([param: NotEmptyGuid] Guid ProductId, [param: Range(typeof(decimal), "0.000001", "999999999999.99")] decimal Quantity, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal UnitCost, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal? UnitPrice = null, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal? Mrp = null);
public sealed record StockInRequest([param: NotEmptyGuid] Guid CompanyId, [param: StringLength(100)] string? StockInNumber, [param: BusinessDate] DateOnly StockInDate, [param: StringLength(500)] string Notes, [param: Required, MinLength(1)] List<StockInLineRequest> Products);
public sealed record PaymentRequest([param: BusinessDate] DateOnly PaymentDate, [param: Range(typeof(decimal), "0.01", "999999999999.99")] decimal PaidAmount, [param: Required, StringLength(40)] string Method, [param: StringLength(120)] string Reference, [param: StringLength(120)] string? BankName = null, [param: BusinessDate] DateOnly? ChequeDate = null);
public sealed record OrderLineRequest([param: NotEmptyGuid] Guid ProductId, [param: Range(typeof(decimal), "0.000001", "999999999999.99")] decimal Quantity, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal FreeIssueQuantity, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal UnitPrice);
public sealed record OrderRequest([param: NotEmptyGuid] Guid ShopId, [param: NotEmptyGuid] Guid SalesRepId, [param: Required, StringLength(100)] string OrderNumber, [param: BusinessDate] DateOnly OrderDate, [param: BusinessDate] DateOnly DeliveryDate, [param: StringLength(500)] string DeliveryAddress, [param: StringLength(500)] string Notes, [param: Required, MinLength(1)] List<OrderLineRequest> Products);
public sealed record DeliveryLineRequest([param: NotEmptyGuid] Guid ProductId, [param: Range(typeof(decimal), "0.000001", "999999999999.99")] decimal Quantity);
public sealed record CompleteOrdersRequest([param: Required, MinLength(1)] List<Guid> OrderIds, [param: BusinessDate] DateOnly DeliveryDate, [param: Required, MinLength(1)] List<DeliveryLineRequest> Products);
public sealed record ChequeRequest([param: NotEmptyGuid] Guid ShopId, Guid? OrderId, [param: Required, StringLength(100)] string ChequeNumber, [param: Required, StringLength(120)] string BankName, [param: Range(typeof(decimal), "0.01", "999999999999.99")] decimal Amount, [param: BusinessDate] DateOnly ChequeDate, [param: Required] string Status, [param: Range(0, 365)] int RemindBeforeDays, [param: StringLength(500)] string Notes);
public sealed record CreateDepositAccountRequest([param: NotEmptyGuid] Guid CompanyId, [param: BusinessDate] DateOnly Date, [param: Required] string Type, [param: Required, StringLength(160)] string Account, [param: Range(typeof(decimal), "0.01", "999999999999.99")] decimal Total, [param: Range(typeof(decimal), "0", "999999999999.99")] decimal Paid, string PaymentMethod = "");
public sealed record AddDepositAccountPaymentRequest([param: BusinessDate] DateOnly PaymentDate, [param: Range(typeof(decimal), "0.01", "999999999999.99")] decimal Amount, [param: Required] string Method, [param: StringLength(120)] string Reference = "");
