namespace Distributor.Api.Contracts;

public sealed record LoginRequest(string Username, string Password);
public sealed record UpdateAdminCredentialsRequest(string Username, string CurrentPassword, string? NewPassword);
public sealed record CreateUserRequest(Guid? CompanyId, string Name, string Username, string Password, string Role, string? Territory = null, bool Active = true, string Address = "", string Nic = "", string Phone = "", string Email = "", decimal? MonthlyTarget = null);
public sealed record UpdateUserRequest(Guid? CompanyId, string Name, string Role, bool Active, string? Territory = null, string Address = "", string Nic = "", string Phone = "", string Email = "", decimal? MonthlyTarget = null);
public sealed record ChangePasswordRequest(string CurrentPassword, string NewPassword);
public sealed record AdminResetPasswordRequest(string NewPassword);
public sealed record BrandingSettingsRequest(string Name, string LogoDataUrl = "");
public sealed record CompanyRequest(string Code, string Name, string ContactName, string Phone, string Address, bool Active = true);
public sealed record ShopRequest(Guid CompanyId, string Code, string Name, string ContactName, string Phone, string Address, string City, decimal CreditLimit, bool Active = true);
public sealed record ProductRequest(Guid CompanyId, string Sku, string Barcode, string Name, string Category, decimal SellingPrice, decimal CostPrice, decimal ReorderLevel, DateOnly? ExpiryDate, decimal OpeningStock = 0, bool Active = true);
public sealed record StockAdjustmentRequest(decimal Quantity, string Direction, string Notes, string? Reason = null);
public sealed record StockInLineRequest(Guid ProductId, decimal Quantity, decimal UnitCost, decimal? UnitPrice = null);
public sealed record StockInRequest(Guid CompanyId, string StockInNumber, DateOnly StockInDate, string Notes, List<StockInLineRequest> Products);
public sealed record PaymentRequest(DateOnly PaymentDate, decimal PaidAmount, string Method, string Reference, string? BankName = null, DateOnly? ChequeDate = null);
public sealed record OrderLineRequest(Guid ProductId, decimal Quantity, decimal FreeIssueQuantity, decimal UnitPrice);
public sealed record OrderRequest(Guid ShopId, Guid SalesRepId, string OrderNumber, DateOnly OrderDate, DateOnly DeliveryDate, string DeliveryAddress, string Notes, List<OrderLineRequest> Products);
public sealed record DeliveryLineRequest(Guid ProductId, decimal Quantity);
public sealed record CompleteOrdersRequest(List<Guid> OrderIds, DateOnly DeliveryDate, List<DeliveryLineRequest> Products);
public sealed record ChequeRequest(Guid ShopId, Guid? OrderId, string ChequeNumber, string BankName, decimal Amount, DateOnly ChequeDate, string Status, int RemindBeforeDays, string Notes);
